import type { Metadata } from "next";
import "../global.css";
import Provider from "@/utils/Providers";

export const metadata: Metadata = {
  title: "Pet Match",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
