import Header from "@/components/header";
import type { Metadata } from "next";
import "../global.css"
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import Footer from "@/components/footer";


export const metadata: Metadata = {
  title: "Pet Match",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)
{
  const queryClient = new QueryClient();
  return (
    <html>
      <body>
        {/* <QueryClientProvider client={queryClient}> */}
          <Header />
          {children}
          <Footer />
        {/* </QueryClientProvider> */}
      </body>
    </html>
  );
}
